[package]
name = "appit"
version = "0.1.0"
edition = "2021"


[features]
default = ["x11", "wayland", "wayland-dlopen"]
wayland-csd-adwaita = ["winit/wayland-csd-adwaita"]
x11 = ["winit/x11"]
wayland = ["winit/wayland"]
wayland-dlopen = ["winit/wayland-dlopen"]

[dependencies]
winit = { version = "0.29.3", default-features = false, features = ["rwh_05"] }
