[package]
name = "appit"
version = "0.1.1"
edition = "2021"
description = "A math library specialized for 2d screen graphics."
repository = "https://github.com/khonsulabs/appit"
license = "MIT OR Apache-2.0"
keywords = ["windowing", "winit"]
categories = ["gui"]
readme = "./README.md"

[features]
default = ["x11", "wayland", "wayland-dlopen"]
wayland-csd-adwaita = ["winit/wayland-csd-adwaita"]
x11 = ["winit/x11"]
wayland = ["winit/wayland"]
wayland-dlopen = ["winit/wayland-dlopen"]

[dependencies]
winit = { version = "0.29.3", default-features = false, features = ["rwh_05"] }
